import { NextRequest, NextResponse } from 'next/server'
import crypto from 'crypto'
import { createClient } from '@supabase/supabase-js'
import { detectCrisis, CRISIS_RESPONSE } from '@/lib/whatsapp/crisis'
import { sendWhatsAppMessage } from '@/lib/whatsapp/send'
import { createWhatsAppUser } from '@/lib/whatsapp/createWhatsAppUser'

const SITE = process.env.NEXT_PUBLIC_SITE_URL ?? 'https://planetsorted.com'

const TOOL_KEYWORDS: Record<string, string> = {
  TAX: 'adhd-tax-calculator',
  AUTOPILOT: 'financial-autopilot',
  CLARITY: 'decision-paralysis-solver',
  DOPAMINE: 'dopamine-menu-generator',
  TRIAGE: 'task-triage',
  RSD: 'rsd-response-scripts',
  SENSORY: 'sensory-audit',
  BURNOUT: 'burnout-assessment',
}

export async function GET(req: NextRequest) {
  const { searchParams } = new URL(req.url)
  if (
    searchParams.get('hub.mode') === 'subscribe' &&
    searchParams.get('hub.verify_token') === process.env.WHATSAPP_VERIFY_TOKEN
  ) {
    return new NextResponse(searchParams.get('hub.challenge'), { status: 200 })
  }
  return new NextResponse('Forbidden', { status: 403 })
}

export async function POST(req: NextRequest) {
  try {
    const body = await req.json()
    const message = body?.entry?.[0]?.changes?.[0]?.value?.messages?.[0]
    if (!message || message.type !== 'text') return NextResponse.json({ status: 'ignored' })

    const from: string = message.from
    const text: string = message.text.body.trim()

    // Safety-critical — always plain text, never a card, no exceptions.
    if (detectCrisis(text)) {
      await sendWhatsAppMessage(from, CRISIS_RESPONSE)
      return NextResponse.json({ status: 'crisis' })
    }

    const verb = text.toUpperCase()
    const sb = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.SUPABASE_SERVICE_ROLE_KEY!)

    const cacheBust = Date.now()
    const START_URL = `${SITE}/r/start?v=${cacheBust}`
    const GOODBYE_URL = `${SITE}/r/goodbye?v=${cacheBust}`

    // ── Consent commands — isolated on purpose.
    if (verb === 'STOP') {
      await sb.from('users').update({ whatsapp_opted_out: true }).eq('whatsapp_number', from)
      await sendWhatsAppMessage(from, GOODBYE_URL, GOODBYE_URL)
      return NextResponse.json({ status: 'ok' })
    }
    if (verb === 'START') {
      await sb.from('users').update({ whatsapp_opted_out: false }).eq('whatsapp_number', from)
      await sendWhatsAppMessage(from, START_URL, START_URL)
      return NextResponse.json({ status: 'ok' })
    }
    if (verb === 'STOPWEEKLY') {
      await sb.from('users').update({ weekly_opted_in: false }).eq('whatsapp_number', from)
      await sendWhatsAppMessage(from, GOODBYE_URL, GOODBYE_URL)
      return NextResponse.json({ status: 'ok' })
    }
    if (verb === 'STARTWEEKLY') {
      await sb.from('users').update({ weekly_opted_in: true }).eq('whatsapp_number', from)
      await sendWhatsAppMessage(from, START_URL, START_URL)
      return NextResponse.json({ status: 'ok' })
    }

    // ── QR / click-to-chat account linking — CONNECT-<userId>.<expiry>.<sig>.
    //    Sent from the pre-filled wa.me link generated by /api/whatsapp/connect-qr.
    //    Sits before the WhatsApp-first signup check below: this number likely has
    //    no existing row yet (that's the whole point), so it must not be treated
    //    as a brand-new WhatsApp-first signup attempt.
    if (/^CONNECT-/i.test(text)) {
      const token = text.slice(text.indexOf('-') + 1)
      const [tokenUserId, expiryStr, sig] = token.split('.')
      const expiry = Number(expiryStr)
      const expectedSig = tokenUserId && expiryStr
        ? crypto.createHmac('sha256', process.env.SUPABASE_SERVICE_ROLE_KEY!).update(`${tokenUserId}.${expiryStr}`).digest('hex').slice(0, 12)
        : null

      if (!tokenUserId || !expiry || !sig || sig !== expectedSig || Date.now() / 1000 > expiry) {
        await sendWhatsAppMessage(from, 'That connect code has expired or is invalid. Please generate a new one from your dashboard Settings.')
        return NextResponse.json({ status: 'invalid_connect_token' })
      }

      const { data: updatedRows, error: updateError } = await sb
        .from('users')
        .update({ whatsapp_number: from, whatsapp_verified: true, whatsapp_opted_out: false })
        .eq('user_id', tokenUserId)
        .select('user_id')

      if (updateError) {
        console.error('[CONNECT update error]', updateError)
        await sendWhatsAppMessage(from, 'This WhatsApp number is already linked to a different account.')
        return NextResponse.json({ status: 'connect_conflict' })
      }

      if (!updatedRows || updatedRows.length === 0) {
        const { data: authUserData } = await sb.auth.admin.getUserById(tokenUserId)
        const { error: insertError } = await sb.from('users').upsert({
          user_id: tokenUserId,
          first_name: authUserData?.user?.user_metadata?.first_name || '',
          email: authUserData?.user?.email || '',
          whatsapp_number: from,
          whatsapp_verified: true,
          weekly_opted_in: false,
          whatsapp_opted_out: false,
        }, { onConflict: 'whatsapp_number' })

        if (insertError) {
          console.error('[CONNECT insert error]', insertError)
          await sendWhatsAppMessage(from, 'This WhatsApp number is already linked to a different account.')
          return NextResponse.json({ status: 'connect_conflict' })
        }
      }

      await sendWhatsAppMessage(from, 'Your WhatsApp is now connected to PLANET SOR7ED ✓')
      return NextResponse.json({ status: 'connected' })
    }

    // ── WhatsApp-first signup — no email required to get started.
    //    Sits after consent commands (STOP must always work, registered or not)
    //    and before LOGIN/tool/article handling (those need an account to mean anything).
    const { data: existingUser } = await sb
      .from('users')
      .select('email')
      .eq('whatsapp_number', from)
      .maybeSingle()

    if (!existingUser) {
      const { data: pending } = await sb
        .from('whatsapp_pending_signups')
        .select('id')
        .eq('phone', from)
        .maybeSingle()

      if (!pending) {
        await sb.from('whatsapp_pending_signups').insert({ phone: from })
        await sendWhatsAppMessage(from, "Welcome to PLANET SOR7ED. What's your first name?")
        return NextResponse.json({ status: 'awaiting_name' })
      }

      const firstName = text.trim()
      await createWhatsAppUser(from, firstName)
      await sb.from('whatsapp_pending_signups').delete().eq('phone', from)
      await sendWhatsAppMessage(
        from,
        `Nice to meet you, ${firstName}. You're in — text ${Object.keys(TOOL_KEYWORDS).join(', ')} to run a tool, or any keyword to get a protocol.`
      )
      return NextResponse.json({ status: 'registered' })
    }

    // ── LOGIN — real magic link pushed straight to WhatsApp, no email typing.
    //    Sent as plain text (no preview_url): a preview fetch would hit Supabase's
    //    verify endpoint and burn the one-time token before the user taps it.
    if (verb === 'LOGIN') {
      const { data: linkData, error: linkError } = await sb.auth.admin.generateLink({
        type: 'magiclink',
        email: existingUser.email,
        options: { redirectTo: `${SITE}/auth/callback` },
      })
      const link = linkData?.properties?.action_link
      if (link && !linkError) {
        await sendWhatsAppMessage(from, link)
      } else {
        console.error('[LOGIN generateLink error]', linkError)
        const url = `${SITE}/signup`
        await sendWhatsAppMessage(from, url, url)
      }
      return NextResponse.json({ status: 'ok' })
    }

    // Strip legacy action prefixes (SAVE, RUN, ARTICLE, AUDIO) if present
    const cleanText = text.replace(/^(SAVE|RUN|ARTICLE|AUDIO)\s+/i, '').trim()
    const cleanVerb = cleanText.toUpperCase()

    // ── Known tool keyword → that tool's card
    if (TOOL_KEYWORDS[cleanVerb]) {
      const url = `${SITE}/r/${TOOL_KEYWORDS[cleanVerb]}?v=${cacheBust}`
      await sendWhatsAppMessage(from, url, url)
      return NextResponse.json({ status: 'ok' })
    }

    // ── Known article keyword or slug → that article's card
    const { data: article } = await sb
      .from('protocols')
      .select('slug')
      .eq('status', 'Published')
      .or(`keyword.ilike.${cleanVerb},slug.ilike.${cleanText.toLowerCase()}`)
      .maybeSingle()

    if (article) {
      const url = `${SITE}/r/${article.slug}?v=${cacheBust}`
      await sendWhatsAppMessage(from, url, url)
      return NextResponse.json({ status: 'ok' })
    }

    // ── HELP / MENU / unrecognized word / first contact —
    //    all collapse to exactly one universal fallback card.
    await sendWhatsAppMessage(from, START_URL, START_URL)
    return NextResponse.json({ status: 'ok' })

  } catch (err) {
    console.error('[Webhook error]', err)
    return NextResponse.json({ status: 'error_logged' }, { status: 200 })
  }
}
